# Welcome to Serverless!
#
# This file is the main config file for your service.
#
#    docs.serverless.com

service: spacebiz-backend

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10

# you can overwrite defaults here
  stage: dev
  region: us-east-1

functions:
  worldstate: # 1: FUNCTION NAME
    handler: handler.worldstate # 2: CODE HOOK FOR FUNCTION IN THE JS
    events:
      - http: 
        # Need two indents apparently?!
          path: worldstate #3:  EXPOSED API PATH
          method: get
          cors: true # <-- to permit access from a frontend on another domain